baseURL = "https://sdttttt.github.io/"
languageCode = "zh-cn"
title = "SDTTTTT"

theme = "rocinante"

paginate = 3

# Number of characters to show in summary.
summaryLength = 1

[markup]
  [markup.highlight]
    style = "monokailight"
  [markup.goldmark.renderer]
    unsafe= true

[params]
  favicon = "/laopo.png"
  mainSections = ["posts", "photos"]
  email = "760159537@qq.com"
  smart_email_link = ["Email"]
  about = """
  Design and execute.
"""

  [[params.links]]
    [[params.links.link]]
      name = "About"
      href = "/about"
      new_tab = true
    
    [[params.links.link]]
      name = "Github"
      href = "https://github.com/sdttttt"
      new_tab = true
    
    [[params.links.link]]
      name = "Twitter"
      href = "https://twitter.com/kaierxs"
      new_tab = true
    
    [[params.links.link]]
      name = "Bilibili"
      href = "https://space.bilibili.com/27781539"
      new_tab = true