baseURL = "https://sdttttt.github.io/"
languageCode = "zh-cn"
title = "SDTTTTT"

theme = "rocinante"

paginate = 5

# Number of characters to show in summary.
summaryLength = 1

[markup]
  [markup.highlight]
    style = "monokailight"
  [markup.goldmark.renderer]
    unsafe= true


[params]
  favicon = "/rust.png"
  mainSections = ["posts", "photos"]
  email = "760159537@qq.com"
  smart_email_link = ["Email"]
  about = """
  Hi! I'm **SDTTTTT**, my research direction is distributed system. Here is my blog, I will record some learning content here, as well as some ideas. If you want to find me, please use **Telegram**. 
At the same time, I also like Japanese animation. **（//▽//）**

<img src="https://gitee.com/sdttttt/images/raw/master//haha.gif" width="33%" />
"""

  [[params.links]]
    
    [[params.links.link]]
      name = "About"
      href = "/about"
      new_tab = true
    
    [[params.links.link]]
      name = "Tags"
      href = "/tags"
      new_tab = true

  [[params.links]]

    [[params.links.link]]
      name = "Github"
      href = "https://github.com/sdttttt"
      new_tab = true
    
    [[params.links.link]]
      name = "Twitter"
      href = "https://twitter.com/kaierxs"
      new_tab = true
    
    [[params.links.link]]
      name = "Telegram"
      href = "https://t.me/tohkashiina"
      new_tab = true

    [[params.links.link]]
      name = "Bilibili"
      href = "https://space.bilibili.com/27781539"
      new_tab = true