baseURL = "https://sdttttt.github.io/"
languageCode = "zh-cn"
title = "SDTTTTT"

themesdir = "themes"
theme = "eiio"

paginate = 15

preserveTaxonomyNames = false
disablePathToLower = true
hasCJKLanguage = true
[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  hljsStyle="atom-one-dark" #code highlightjs css style . See [Style List](https://github.com/highlightjs/highlight.js/tree/master/src/styles "CSS Style list")

  showNextAndPrePost = false #Is Show Next and Previous Post Button
  description = "**None**"
  author = "sdttttt"
  github ="sdttttt"
  email="sdttttt@outlook.com"
  twitter="your twitter name" 
  securityPolicy = false #disable https content security policy
  footerRight="Your tips content" #footer right content
  addthisID="addthis.com sharder plugin id"
  mainSections = ['page']
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"