baseURL = "https://sdttttt.github.io/"
languageCode = "zh-cn"
title = "SDTTTTT"

themesdir = "themes"
theme = "prav"

paginate = 5

# Set unsafe mode to allow markdownify to work with goldmark
# This is important. Please do not delete. It is used to re-render markdown
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# The settings below are used throughout the theme.
# Please update!
[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"

  title = "SDTTTTT"
  tagline = "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
  author = "Sdttttt"
  authorImgPath = "/me.png"
  authorBlurb = "突如其来的变故使得本就不富裕的晦气小伙雪上加霜."

# If you do not want a social icon, just comment it out
# Please update the example values!
[social]
  email = "mailto:sdttttt@outlook.com"
  facebook = "https://www.facebook.com/sdzzzzz"
  twitter = "http://twitter.com/shiina38092638"
  github = "https://github.com/sdttttt"
  telegram = "https://t.me/tohkashiina"
  #linkedin = "http://uk.linkedin.com/in/example"