baseURL: "https://sdttttt.github.io/"
languageCode: "zh-cn"
title: "SDTTTTT"

theme: "hugo-tania-main"

paginate: 999

DisqusShortname: "sdttttt"

params:
    titleEmoji: ""


markup:
    highlight:
        noClasses: false
        lineNos: true
    goldmark:
        renderer:
            unsafe: true
