name: Update gist with WakaTime stats
on:
  push:
    
  schedule:
    - cron: "0 * * * *"

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: d78d2e5623197fc743de8516c0d33ba1
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
