name: Update gist with WakaTime stats
on:
  push:
  schedule:
    - cron: "0 * * * 0"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIST_ID: 8b9bfdee336834dcae149f81a405aaf6
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
